from __future__ import annotations

import re
from typing import Any

from olx.browser_session import (
    PT_ACCOUNT_URL,
    PT_HOME_URL,
    dismiss_cookie_banner_if_present,
    get_current_context_cookies,
    open_olx_browser_context,
    open_olx_page,
)
from olx.cookies import normalize_cookies
from olx.proxy_bridge import build_bridge_proxy_settings


def get_auth_cookie_names(cookies: list[dict[str, Any]]) -> list[str]:
    important_names = {
        "authstate",
        "sid",
        "access_token",
        "auth_state",
        "user_uuid",
        "user_id",
        "phpsessid",
    }
    found: list[str] = []
    for cookie in cookies:
        name = str(cookie.get("name", "")).lower()
        if name in important_names:
            found.append(name)
    return found


def detect_cloudfront_or_block_page(url: str, title: str, body_text: str) -> bool:
    haystack = f"{url}\n{title}\n{body_text}".lower()
    markers = [
        "403 error",
        "the request could not be satisfied",
        "request blocked",
        "generated by cloudfront",
        "cloudfront",
        "access denied",
    ]
    return any(marker in haystack for marker in markers)


def extract_profile_name(body_text: str) -> str | None:
    body = " ".join((body_text or "").split())

    patterns = [
        r"Olá,\s*([A-ZÀ-Ý][\wÀ-ÿ' -]{1,40})",
        r"Ola,\s*([A-ZÀ-Ý][\wÀ-ÿ' -]{1,40})",
        r"Bem-vindo,\s*([A-ZÀ-Ý][\wÀ-ÿ' -]{1,40})",
        r"Hello,\s*([A-ZÀ-Ý][\wÀ-ÿ' -]{1,40})",
    ]

    for pattern in patterns:
        match = re.search(pattern, body, flags=re.IGNORECASE)
        if match:
            value = (match.group(1) or "").strip(" -,:")
            if value:
                return value

    return None


def detect_logged_in_from_page(
    url: str,
    title: str,
    body_text: str,
    auth_cookie_names: list[str],
) -> bool:
    lowered_url = (url or "").lower()
    lowered_title = (title or "").lower()
    lowered_body = (body_text or "").lower()

    if detect_cloudfront_or_block_page(url, title, body_text):
        return False

    login_signals = [
        "iniciar sessão",
        "entrar",
        "login",
        "sign in",
        "log in",
        "criar conta",
    ]

    account_signals = [
        "a tua conta",
        "a minha conta",
        "minha conta",
        "my account",
        "mensagens",
        "favoritos",
        "sair",
        "logout",
    ]

    redirected_to_login = "login" in lowered_url or "auth" in lowered_url
    has_login_cta = any(signal in lowered_body or signal in lowered_title for signal in login_signals)
    has_account_signal = any(signal in lowered_body or signal in lowered_title for signal in account_signals)
    has_auth_cookies = len(auth_cookie_names) > 0
    on_account_area = "/myaccount" in lowered_url or "/conta" in lowered_url or "/account" in lowered_url

    if redirected_to_login:
        return False

    if has_login_cta and not has_account_signal:
        return False

    if has_account_signal:
        return True

    if has_auth_cookies and on_account_area and not has_login_cta:
        return True

    return False


async def check_account_with_proxy(
    cookies_json: str,
    proxy_text: str,
    *,
    headless: bool = True,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "ok": False,
        "status": "failed",
        "final_url": None,
        "page_title": None,
        "auth_cookie_names": [],
        "bridge_server": None,
        "profile_name": None,
        "error": None,
    }

    try:
        bridge_proxy = build_bridge_proxy_settings(proxy_text)
        result["bridge_server"] = bridge_proxy["server"]
        normalize_cookies(cookies_json)
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        return result

    try:
        async with open_olx_browser_context(
            cookies_json=cookies_json,
            proxy_text=proxy_text,
            headless=headless,
        ) as (_, context):
            page = await open_olx_page(
                context,
                PT_HOME_URL,
                timeout=90000,
                wait_after_ms=3000,
            )

            await dismiss_cookie_banner_if_present(page)
            await page.wait_for_timeout(1000)

            await page.goto(
                PT_ACCOUNT_URL,
                wait_until="domcontentloaded",
                timeout=90000,
            )
            await page.wait_for_timeout(4000)

            result["final_url"] = page.url

            try:
                result["page_title"] = await page.title()
            except Exception:
                result["page_title"] = None

            try:
                body_text = await page.locator("body").inner_text(timeout=5000)
            except Exception:
                body_text = ""

            current_cookies = await get_current_context_cookies(context)
            auth_cookie_names = get_auth_cookie_names(current_cookies)
            result["auth_cookie_names"] = auth_cookie_names

            profile_name = extract_profile_name(body_text)
            if profile_name:
                result["profile_name"] = profile_name

            is_logged_in = detect_logged_in_from_page(
                url=page.url,
                title=result["page_title"] or "",
                body_text=body_text,
                auth_cookie_names=auth_cookie_names,
            )

            if is_logged_in:
                result["ok"] = True
                result["status"] = "connected"
                return result

            result["status"] = "failed"
            result["error"] = "OLX account page did not confirm authenticated session"
            return result

    except Exception as exc:
        message = str(exc).lower()
        result["error"] = str(exc)

        proxy_error_markers = [
            "proxy",
            "tunnel",
            "timeout",
            "net::err_proxy",
            "browser has been closed",
            "socks",
            "connection refused",
            "connection reset",
            "net::err",
        ]

        if any(marker in message for marker in proxy_error_markers):
            result["status"] = "failed"
        else:
            result["status"] = "failed"

        return result