from __future__ import annotations

from olx.message_sender_debug import normalize_text

LOGIN_HINT_SELECTORS = [
    'a[href*="login"]',
    'button:has-text("Entrar")',
    'button:has-text("Iniciar sessão")',
    'text=Entrar',
    'text=Iniciar sessão',
]

SOFT_ERROR_TEXTS = [
    "Ups, algo não está bem",
    "Atualiza esta página ou volta à página principal",
]


async def page_body_text(page) -> str:
    try:
        text = await page.locator("body").inner_text(timeout=3000)
        return normalize_text(text)
    except Exception:
        return ""


async def is_cloudfront_block_page(page) -> bool:
    try:
        title = await page.title()
    except Exception:
        title = ""

    try:
        body_text = await page_body_text(page)
    except Exception:
        body_text = ""

    haystack = f"{(title or '').lower()}\n{(body_text or '').lower()}"

    markers = [
        "403 error",
        "the request could not be satisfied",
        "request blocked",
        "generated by cloudfront",
        "cloudfront",
    ]

    return any(marker in haystack for marker in markers)


async def handle_olx_soft_error_page(page) -> bool:
    body_text = await page_body_text(page)
    if not any(text.lower() in body_text.lower() for text in SOFT_ERROR_TEXTS):
        return False

    candidates = [
        page.get_by_role("button", name="Atualizar").first,
        page.locator("button:has-text('Atualizar')").first,
        page.locator("text=Atualizar").first,
    ]

    for locator in candidates:
        try:
            if await locator.count() == 0:
                continue
            if not await locator.is_visible():
                continue

            await locator.scroll_into_view_if_needed()

            try:
                await locator.click(timeout=3000)
            except Exception:
                await locator.click(force=True, timeout=3000)

            try:
                await page.wait_for_load_state("networkidle", timeout=8000)
            except Exception:
                pass

            await page.wait_for_timeout(1500)
            return True
        except Exception:
            continue

    return True


async def has_login_hint(page) -> bool:
    for selector in LOGIN_HINT_SELECTORS:
        try:
            locator = page.locator(selector).first
            if await locator.count() == 0:
                continue
            if await locator.is_visible():
                return True
        except Exception:
            continue
    return False