from __future__ import annotations

from olx.markets.message_helpers import get_login_texts
from olx.message_sender_debug import normalize_text


DEFAULT_PAGE_MARKET = "olx_pt"


def _build_login_hint_selectors(market_code: str = DEFAULT_PAGE_MARKET) -> list[str]:
    values: list[str] = [
        'a[href*="login"]',
        'form[action*="login"]',
        'input[type="password"]',
    ]

    seen = set(values)
    for text in get_login_texts(market_code):
        escaped = text.replace('"', '\\"')
        candidates = [
            f'button:has-text("{escaped}")',
            f'a:has-text("{escaped}")',
            f'text={text}',
        ]
        for item in candidates:
            if item not in seen:
                seen.add(item)
                values.append(item)

    return values


def _build_soft_error_texts(market_code: str = DEFAULT_PAGE_MARKET) -> list[str]:
    defaults = {
        "olx_pt": [
            "Ups, algo não está bem",
            "Atualiza esta página ou volta à página principal",
        ],
        "olx_pl": [
            "Ups, coś poszło nie tak",
            "Odśwież stronę lub wróć do strony głównej",
        ],
    }
    return defaults.get(market_code, defaults["olx_pt"])


def _build_refresh_button_texts(market_code: str = DEFAULT_PAGE_MARKET) -> list[str]:
    defaults = {
        "olx_pt": ["Atualizar"],
        "olx_pl": ["Odśwież"],
    }
    return defaults.get(market_code, defaults["olx_pt"])


async def page_body_text(page) -> str:
    try:
        text = await page.locator("body").inner_text(timeout=3000)
        return normalize_text(text)
    except Exception:
        return ""


async def is_cloudfront_block_page(page) -> bool:
    try:
        title = await page.title()
    except Exception:
        title = ""

    try:
        body_text = await page_body_text(page)
    except Exception:
        body_text = ""

    haystack = f"{(title or '').lower()}\n{(body_text or '').lower()}"

    markers = [
        "403 error",
        "the request could not be satisfied",
        "request blocked",
        "generated by cloudfront",
        "cloudfront",
    ]

    return any(marker in haystack for marker in markers)


async def handle_olx_soft_error_page(
    page,
    *,
    market_code: str = DEFAULT_PAGE_MARKET,
) -> bool:
    body_text = await page_body_text(page)
    soft_error_texts = _build_soft_error_texts(market_code)

    if not any(text.lower() in body_text.lower() for text in soft_error_texts):
        return False

    candidates = []
    for text in _build_refresh_button_texts(market_code):
        candidates.extend(
            [
                page.get_by_role("button", name=text).first,
                page.locator(f'button:has-text("{text}")').first,
                page.locator(f"text={text}").first,
            ]
        )

    for locator in candidates:
        try:
            if await locator.count() == 0:
                continue
            if not await locator.is_visible():
                continue

            await locator.scroll_into_view_if_needed()

            try:
                await locator.click(timeout=3000)
            except Exception:
                await locator.click(force=True, timeout=3000)

            try:
                await page.wait_for_load_state("networkidle", timeout=8000)
            except Exception:
                pass

            await page.wait_for_timeout(1500)
            return True
        except Exception:
            continue

    return True


async def has_login_hint(
    page,
    *,
    market_code: str = DEFAULT_PAGE_MARKET,
) -> bool:
    for selector in _build_login_hint_selectors(market_code):
        try:
            locator = page.locator(selector).first
            if await locator.count() == 0:
                continue
            if await locator.is_visible():
                return True
        except Exception:
            continue
    return False