from __future__ import annotations

from typing import Any

from playwright.async_api import async_playwright

from olx.browser_session import PT_HOME_URL, dismiss_cookie_banner_if_present
from olx.proxy_bridge import build_bridge_proxy_settings


def _looks_blocked(title: str, body_text: str, url: str) -> bool:
    haystack = f"{title}\n{body_text}\n{url}".lower()
    markers = [
        "403 error",
        "the request could not be satisfied",
        "request blocked",
        "generated by cloudfront",
        "cloudfront",
        "access denied",
    ]
    return any(marker in haystack for marker in markers)


async def check_proxy_alive(
    proxy_text: str,
    *,
    headless: bool = True,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "ok": False,
        "status": "failed",
        "final_url": None,
        "page_title": None,
        "bridge_server": None,
        "error": None,
    }

    try:
        bridge_proxy = build_bridge_proxy_settings(proxy_text)
        result["bridge_server"] = bridge_proxy["server"]
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        return result

    browser = None
    context = None

    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(
                headless=headless,
                proxy=bridge_proxy,
            )
            context = await browser.new_context()
            page = await context.new_page()

            await page.goto(PT_HOME_URL, wait_until="domcontentloaded", timeout=90000)
            await page.wait_for_timeout(3000)

            try:
                await dismiss_cookie_banner_if_present(page)
            except Exception:
                pass

            await page.wait_for_timeout(1000)

            result["final_url"] = page.url

            try:
                result["page_title"] = await page.title()
            except Exception:
                result["page_title"] = None

            try:
                body_text = await page.locator("body").inner_text(timeout=5000)
            except Exception:
                body_text = ""

            if _looks_blocked(result["page_title"] or "", body_text or "", page.url or ""):
                result["status"] = "failed"
                result["error"] = "OLX/CloudFront blocked the request"
                return result

            body_len = len((body_text or "").strip())
            if page.url and body_len > 100:
                result["ok"] = True
                result["status"] = "working"
                return result

            result["status"] = "failed"
            result["error"] = "Proxy opened page, but OLX content was not confirmed"
            return result

    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        return result

    finally:
        try:
            if context:
                await context.close()
        except Exception:
            pass

        try:
            if browser:
                await browser.close()
        except Exception:
            pass